import test,{before,after}from'node:test'
import assert from'node:assert/strict'
import{spawn}from'node:child_process'
import{chromium,firefox}from'playwright'
import{createFixture}from'../fixtures/server.mjs'
let fixture,server,browser,log='';const base='http://127.0.0.1:3106'
const block=route=>['image','media'].includes(route.request().resourceType())||/googletagmanager|google-analytics|google.com/.test(new URL(route.request().url()).hostname)?route.abort():route.continue()
const hydrated=page=>page.waitForFunction(()=>{const n=document.querySelector('#__nuxt')?.__vue_app__?.$nuxt;return n?.isHydrating===false&&!n.payload.error})
before(async()=>{fixture=await createFixture();server=spawn(process.execPath,['.output/server/index.mjs'],{env:{...process.env,PORT:'3106',HOST:'127.0.0.1',NUXT_PUBLIC_GRAPHQL_ENDPOINT:fixture.url},stdio:['ignore','pipe','pipe']});for(const stream of[server.stdout,server.stderr])stream.on('data',d=>log+=d);let ready=false;for(let i=0;i<100;i++){try{await fetch(base+'/_nuxt/builds/latest.json');ready=true;break}catch{await new Promise(r=>setTimeout(r,100))}}assert.ok(ready);browser=await chromium.launch()})
after(async()=>{await browser?.close();server?.kill();await fixture?.close();if(fixture?.state.unknown.length)console.error('Unknown fixture requests',fixture.state.unknown);if(process.env.DEBUG_FIXTURE)console.log(log)})
for(const mode of['success','absent','empty-acf','message-error','timeout'])for(const prefix of['','/en'])test(`${mode} ${prefix||'CS'} SSR + zdravá hydratace`,{timeout:30000},async()=>{
 fixture.state.mode=mode;fixture.state.requests=[];const context=await browser.newContext();await context.route('**/*',block)
 try{const page=await context.newPage(),graphql=[],payloads=[];page.on('request',r=>{if(r.url().includes('/graphql'))graphql.push(r.url());if(r.url().includes('_payload.'))payloads.push(r.url())});const res=await page.goto(base+prefix+'/pf');assert.equal(res.status(),200);const html=await res.text();assert.ok(!/class="[^"]*cookieControl/.test(html));assert.equal(res.headers()['set-cookie'],undefined);await hydrated(page);assert.equal(await page.locator('.site-message').count(),mode==='success'?1:0);if(mode==='success')assert.equal(await page.locator('.site-message').innerText(),prefix?'English notice':'Česká hláška');assert.deepEqual(graphql,[]);assert.ok(payloads.length<=1)
 }finally{await context.close()}
})
test('povinné null a chyby vrací 503 po právě dvou pokusech',async()=>{for(const mode of['null','content-error']){fixture.state.mode=mode;fixture.state.requests=[];assert.equal((await fetch(base+'/pf')).status,503);assert.equal(fixture.state.requests.filter(r=>r.operation==='getKlingerPF').length,2)}})
test('neexistující detaily vracejí 404',async()=>{fixture.state.mode='absent';for(const path of['/kariera/fixture-missing','/sluzby/fixture-missing','/partneri/fixture-missing','/katalog-produktu/fixture-missing','/katalog-produktu/product/fixture-missing','/katalog-produktu/vyrobce/fixture-missing'])assert.equal((await fetch(base+path)).status,404,path)})
for(const lang of['cs','en'])test(`všechny statické a dostupné dynamické routy ${lang}`,{timeout:60000},async()=>{
 fixture.state.mode='absent';const prefix=lang==='en'?'/en':'',r=fixture.routes[lang],paths=['/','/o-nas','/kontakty','/reference','/sluzby','/partneri','/kariera','/katalog-produktu','/pf','/kalendare',`/sluzby/${r.service}`,`/partneri/${r.partner}`,`/katalog-produktu/vyrobce/${r.partner}`,`/katalog-produktu/${r.category}`,`/katalog-produktu/product/${r.product}`,'/kariera/fixture-job']
 const context=await browser.newContext();await context.route('**/*',block)
 try{const page=await context.newPage();for(const path of paths){const errors=[],gql=[];const onError=e=>errors.push(e.message),onRequest=q=>{if(q.url().includes('/graphql'))gql.push(q.url())};page.on('pageerror',onError);page.on('request',onRequest);const res=await page.goto(base+(prefix+path).replace(/\/$/,''));assert.equal(res.status(),200,path);await hydrated(page);assert.ok((await page.locator('h1').first().innerText()).length,path);assert.deepEqual(errors,[],path);assert.deepEqual(gql,[],path);page.off('pageerror',onError);page.off('request',onRequest)}}finally{await context.close()}
})
for(const lang of['cs','en'])for(const type of['catalogue','category','product'])test(`opožděná obnova chybějícího payloadu ${lang} ${type}`,async()=>{
 fixture.state.mode='absent';const r=fixture.routes[lang],prefix=lang==='en'?'/en':'',path='/katalog-produktu'+(type==='category'?'/'+r.category:type==='product'?'/product/'+r.product:'')
 const context=await browser.newContext(),queries=[],errors=[];await context.route('**/*',async route=>{const req=route.request();if(req.url().includes('_payload.json'))return route.fulfill({status:503,body:'{}'});if(req.url().includes('/graphql')){queries.push(JSON.parse(req.postData()).query.match(/query\s+(\w+)/)[1]);await new Promise(r=>setTimeout(r,150))}return block(route)})
 try{const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{if(window.top!==window)return;window.__errorFlash=false;new MutationObserver(()=>{if([...document.querySelectorAll('h1')].some(h=>/^50[03]$/.test(h.textContent.trim())))window.__errorFlash=true}).observe(document,{childList:true,subtree:true,characterData:true})});assert.equal((await page.goto(base+prefix+path)).status(),200);await hydrated(page);assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>window.__errorFlash),false);assert.equal(queries.filter(q=>q==='getKlingerNavigation').length,1);for(const q of new Set(queries))assert.equal(queries.filter(x=>x===q).length,1,q)}finally{await context.close()}
})
test('payload i CMS selžou: řízená klientská 503 bez čtení null',async()=>{
 fixture.state.mode='absent';const context=await browser.newContext(),queries=[];await context.route('**/*',r=>{if(r.request().url().includes('_payload.json'))return r.fulfill({status:503,body:''});if(r.request().url().includes('/graphql')){queries.push(JSON.parse(r.request().postData()).query.match(/query\s+(\w+)/)[1]);return r.fulfill({status:503,body:''})}return block(r)})
 try{const page=await context.newPage();assert.equal((await page.goto(base+'/katalog-produktu')).status(),200);await page.getByRole('heading',{name:'503',exact:true}).waitFor();assert.ok(!(await page.locator('body').innerText()).includes('reading'));assert.equal(queries.filter(q=>q==='getKlingerNavigation').length,2)}finally{await context.close()}
})
test('hledání zachovává služby, partnery, produkty i kategorie; prázdný výsledek je platný',async()=>{fixture.state.mode='absent';for(const language of['cs','en'])for(const term of['klinger','fixture-empty']){const res=await fetch(base+(language==='en'?'/en':'')+'/vyhledavani?search='+term);assert.equal(res.status,200);const html=await res.text();if(term==='klinger'){assert.match(html,/search-results/);assert.match(html,/\/sluzby\//);assert.match(html,/\/partneri\//)}else assert.ok(!html.includes('class="search-results"'))}})
test('mobilní menu: Enter, Space, Escape na tlačítku i uvnitř; bez prefetch',async()=>{
 fixture.state.mode='absent';const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true});await context.route('**/*',block)
 try{const page=await context.newPage(),requests=[];page.on('request',r=>requests.push(r.url()));assert.equal((await page.goto(base+'/')).status(),200);await hydrated(page);await page.locator('.cookieControl__Bar').getByRole('button',{name:'Zamítnout',exact:true}).click();const button=page.locator('.hamburger');assert.equal(await page.locator('#navigation').isVisible(),false)
 for(const key of['Enter','Space']){await button.focus();await page.keyboard.press(key);assert.equal(await button.getAttribute('aria-expanded'),'true');await page.keyboard.press('Escape');assert.equal(await button.getAttribute('aria-expanded'),'false')}
 await button.tap();await page.locator('#navigation a').first().focus();await page.keyboard.press('Escape');assert.equal(await button.getAttribute('aria-expanded'),'false');await page.waitForFunction(()=>getComputedStyle(document.querySelector('#navigation')).visibility==='hidden');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)
 const before=requests.length;await page.locator('header .site-logo a').hover();await page.locator('header .site-logo a').focus();await page.waitForTimeout(250);assert.ok(requests.slice(before).every(url=>!url.includes('_payload')&&!url.includes('/graphql')))
 }finally{await context.close()}
})
test('hero varianty mají použitelné rozlišení pro desktop i DPR2 mobil',async()=>{
 fixture.state.mode='absent'
 for(const [width,dpr]of[[390,2],[1440,1]])for(const path of['/o-nas','/kontakty']){
  const context=await browser.newContext({viewport:{width,height:900},deviceScaleFactor:dpr});await context.route('**/*',r=>{if(r.request().resourceType()==='image')return r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="900"/>'});return block(r)})
  try{const page=await context.newPage();assert.equal((await page.goto(base+path)).status(),200);const img=page.locator('.hero picture img');await img.evaluate(el=>el.decode());const selected=await img.evaluate(el=>({src:el.currentSrc,width:Number(el.getAttribute('width')),height:Number(el.getAttribute('height')),srcset:el.srcset}));const dimensions=selected.src.match(/s_(\d+)x(\d+)/);assert.ok(dimensions,selected.src);assert.ok(Number(dimensions[1])>=Math.min(selected.width,width*dpr),selected.src);assert.ok(Math.abs(Number(dimensions[2])/Number(dimensions[1])-selected.height/selected.width)<0.01);for(const variant of selected.srcset.split(','))assert.ok(Number(variant.match(/s_(\d+)x/)[1])>=320);if(path==='/kontakty')assert.equal(Number(dimensions[1]),selected.width)}finally{await context.close()}
 }
})
test('stránkování 15 → 1 → 15 vyvolá právě jeden nový dotaz na kliknutí',async()=>{
 fixture.state.mode='pagination';const context=await browser.newContext();await context.route('**/*',block)
 try{const page=await context.newPage(),queries=[];page.on('request',r=>{if(r.url().includes('/graphql'))queries.push(r.url())});assert.equal((await page.goto(base+'/katalog-produktu/'+fixture.routes.cs.category)).status(),200);await hydrated(page);await page.locator('.cookieControl__Bar').getByRole('button',{name:'Zamítnout',exact:true}).click();assert.equal(await page.locator('.product').count(),15);assert.equal(queries.length,0)
 await page.locator('.button-next').click();await page.getByRole('heading',{name:'Druhá strana',exact:true}).waitFor();assert.equal(await page.locator('.product').count(),1);assert.equal(queries.length,1)
 await page.locator('.button-prev').click();await page.getByRole('heading',{name:'První strana',exact:true}).waitFor();assert.equal(await page.locator('.product').count(),15);assert.equal(queries.length,2)
 }finally{fixture.state.mode='absent';await context.close()}
})
test('jazykový přepínač používá překlad partnera a fallback nepřeloženého produktu už v SSR',async()=>{
 fixture.state.mode='absent';const context=await browser.newContext();await context.route('**/*',block)
 try{const page=await context.newPage();for(const[path,expected]of[[`/partneri/${fixture.routes.cs.partner}`,`/en/partneri/${fixture.routes.en.partner}`],[`/katalog-produktu/product/${fixture.routes.cs.product}`,'/en/katalog-produktu']]){const res=await page.goto(base+path);assert.equal(res.status(),200);assert.ok((await res.text()).includes(`href="${expected}"`));await hydrated(page);assert.equal(await page.locator('header nav.language a').getAttribute('href'),expected)}}finally{await context.close()}
})
