import assert from 'node:assert/strict'
import {chromium} from 'playwright'
import {mkdir,writeFile} from 'node:fs/promises'
const base=process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:3105',out=process.env.MEASUREMENT_OUTPUT||'output/playwright/startup.json',blocked=process.env.BLOCK_MEDIA==='1',results=[]
const browser=await chromium.launch();await mkdir('output/playwright',{recursive:true})
try{for(const path of['/','/en'])for(let sample=1;sample<=3;sample++){
 const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});await context.addCookies(['ncc_c','ncc_e'].map(name=>({name,value:name==='ncc_c'?'necessarygoogle-analytics':'necessary',domain:new URL(base).hostname,path:'/'})))
 await context.route('**/*',r=>{if(/googletagmanager|google-analytics|analytics.google/.test(new URL(r.request().url()).hostname)||(blocked&&['image','media'].includes(r.request().resourceType())))return r.abort();return r.continue()})
 const page=await context.newPage(),errors=[],responses=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=500)errors.push(`${r.status()} ${r.url()}`);responses.push({url:r.url(),status:r.status(),type:r.request().resourceType()})})
 await page.addInitScript(()=>{if(window.top!==window)return;window.__startup={visible:null,opened:null,hydrated:null};const poll=()=>{const n=document.querySelector('#__nuxt')?.__vue_app__?.$nuxt,b=document.querySelector('.hamburger');if(b?.getBoundingClientRect().width)window.__startup.visible??=performance.now();if(document.querySelector('#navigation.visible'))window.__startup.opened??=performance.now();if(n?.isHydrating===false&&!n.payload.error)window.__startup.hydrated??=performance.now();requestAnimationFrame(poll)};requestAnimationFrame(poll)})
 const cdp=await context.newCDPSession(page);await cdp.send('Network.enable');await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:150,downloadThroughput:200000,uploadThroughput:93750});await cdp.send('Emulation.setCPUThrottlingRate',{rate:4})
 try{const res=await page.goto(base+path,{waitUntil:'commit'});assert.equal(res.status(),200);await page.locator('.hamburger').waitFor({state:'visible'});for(let i=0;i<160;i++){await page.locator('.hamburger').tap();await page.waitForTimeout(150);if(await page.locator('#navigation').evaluate(el=>el.classList.contains('visible')))break;if(errors.length)throw Error(errors.join('\n'))}await page.waitForFunction(()=>window.__startup.opened!==null&&window.__startup.hydrated!==null);assert.deepEqual(errors,[]);const data=await page.evaluate(()=>({...window.__startup,ttfb:performance.getEntriesByType('navigation')[0].responseStart,js:performance.getEntriesByType('resource').filter(r=>/\.js(?:\?|$)/.test(r.name)).reduce((sum,r)=>sum+r.encodedBodySize,0)}));results.push({path,sample,...data,graphql:responses.filter(r=>r.url.includes('/graphql')).length,payloads:responses.filter(r=>r.url.includes('_payload.')).length,responses});console.log(path,sample,data.opened)}catch(error){results.push({path,sample,error:error.message,responses});throw error}finally{await context.close()}
}}finally{await browser.close();await writeFile(out,JSON.stringify({base,conditions:{viewport:'390x844',dpr:1,cpu:4,latency:150,download:200000,upload:93750,media:blocked?'blocked':'enabled',cache:'browser cache disabled by routing; CDN not purged',browser:'Chromium',consent:'declined'},results},null,2))}
