import test from 'node:test'
import assert from 'node:assert/strict'
import {withContentPagination} from '../../utils/paginated-content-request.js'
import {collectConnection,getSitemapUrls} from '../../utils/sitemap-content.js'
import {validateContentData} from '../../utils/validate-content-data.js'
test('navigace čte všechny stránky postupně',async()=>{let active=0,max=0;const seen=[];const request=withContentPagination(async input=>{active++;max=Math.max(max,active);seen.push(input.variables);await new Promise(r=>setTimeout(r,1));active--;return{productCategories:{nodes:[{slug:input.variables._cursor_productCategories?'second':'first'}],pageInfo:{hasNextPage:!input.variables._cursor_productCategories,endCursor:'next'}}}});const data=await request({query:'query getKlingerNavigation {}',variables:{language:'CS'}});assert.deepEqual(data.productCategories.nodes.map(x=>x.slug),['first','second']);assert.equal(max,1);assert.equal(seen.length,2)})
for(const scenario of['repeated','missing','pageInfo','nodes'])test(`vadné stránkování ${scenario} vyvolá chybu`,async()=>{let calls=0;const request=withContentPagination(async()=>{calls++;return{productCategories:{nodes:scenario==='nodes'?null:[],pageInfo:scenario==='pageInfo'?null:{hasNextPage:true,endCursor:scenario==='missing'?null:'same'}}}});await assert.rejects(request({query:'query getKlingerNavigation {}',variables:{}}));assert.ok(calls<=2)})
test('vnořené kategorie produktu se dočtou podle ID',async()=>{const requests=[];const load=withContentPagination(async input=>{requests.push(input);return requests.length===1?{products:{nodes:[{id:'product-id',productCategories:{nodes:[{slug:'first'}],pageInfo:{hasNextPage:true,endCursor:'next'}}}]}}:{product:{productCategories:{nodes:[{slug:'second'}],pageInfo:{hasNextPage:false,endCursor:null}}}}});const data=await load({query:'query getProduct {}',variables:{slug:'a'}});assert.deepEqual(data.products.nodes[0].productCategories.nodes.map(x=>x.slug),['first','second']);assert.deepEqual(requests[1].variables,{id:'product-id',after:'next'})})
test('sitemap nesmí vydávat chybu za prázdná data',async()=>{await assert.rejects(collectConnection(async()=>({products:null}),'query',{},'products'));await assert.rejects(getSitemapUrls(async()=>({})))})
test('povinná data null, chybějící ACF a platný prázdný detail',()=>{assert.equal(validateContentData('getKlingerPF',{page:null}),false);assert.equal(validateContentData('getKlingerPF',{page:{title:'PF'}}),false);assert.equal(validateContentData('getCareerDetail',{careers:{nodes:[]}}),true)})
